background_opacity 0.8
confirm_os_window_close 0

# The "Lain" Terminal Colors
foreground #ead8b1
background #000000

# Map "Magenta" to your Pink
color5  #b56a81
color13 #b56a81

# Map "Yellow" to your Cream
color3  #ead8b1
color11 #ead8b1
